# Generated by Django 2.2.18 on 2021-03-22 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('space', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('RENT', 'rent'), ('SALE', 'sale')], default='SALE', max_length=25)),
                ('image1', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image2', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image3', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image4', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('space', models.IntegerField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image2', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image3', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image4', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('space', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=25)),
                ('image1', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image2', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image3', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('image4', models.ImageField(default='default.jpeg', upload_to='houses')),
                ('status', models.CharField(choices=[('RENT', 'rent'), ('SALE', 'sale')], default='SALE', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
